name: Publish on Tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  github:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      -
        name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Create release on GitHub
        run: bundle exec rake release:github
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.danger_github_api_token }}
