name: Test SPM

on:
  push:
    branches: stable
  pull_request:

jobs:
  macos:
    name: Test SPM macOS
    runs-on: macos-12
    steps:
      - 
        name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - 
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - 
        name: Cache SPM
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      -
        name: Test Command
        run: bundle exec rake spm:test_command
